### ISSUE TITLE
Still some problems while updating sysdata.Rda from a french configured computer

### ISSUE THREAD

**Issue by jordanoplante** [iml-assess/catchR#30]
Same problem as yesterday in regard to reading .csv files with commas within columns. It seems that when I'm the one creating `sysdata.Rda`, I get problems.

In this specific example, `gear.cat` is NA and I don't get a proper merge while using the `read.bio()` function.

Also, I think the french description of this gear should me modified to fit what the english description says:

* `engin_fr`: "Seine danoise, écossaise ou pairée (2 navires)"
* `engin_en`: stays the same
* `gear.cat`: stays the same

https://github.com/iml-assess/catchR/blob/f723a376b44f8f143ab4304d86234e43bb9b9952/data-raw/bio_gear.csv#L36

**Comment by elisvb** [comment]
For now, I'm guessing that csv is easier to work with so I kept the current approach and simply replaced all commas, as well as the description of the indicated gear type.

If this happens again we can switch .csv to .dat or so or add a check using the testthat package.
