### ISSUE TITLE
Small error

### ISSUE THREAD

**Issue by jordanoplante** [iml-assess/catchR#33]
Shouldn't it be  `lfcol[1:6]` on line 52?

https://github.com/iml-assess/catchR/blob/f723a376b44f8f143ab4304d86234e43bb9b9952/R/get.samples.R#L39-L54

**Comment by elisvb** [comment]
Well no because it groups OVER all lengths? So for every lf sample ided by [1:5], it will take nj/sum(nj)

**Comment by jordanoplante** [comment]
oops my bad! For some reason I got confused between `mutate` and `summarise`.
