### ISSUE TITLE
Filling the gaps with a useless age-length key

### ISSUE THREAD

**Issue by jordanoplante** [iml-assess/catchR#34]
I have an issue for 2 year-month-opano-gear strata. Let's take one. 

After having selected the samples to use (with the `find.samples` function. Threshold set to 2 samples),  I found out I had 2 age samples (for a total of 4 aged cods, each having a different length).

When performing  the merge at row 143, it resulted that I had only 1 cod from the age sample that had a merge (meaning all other lengths from the age data didn't have a correspondance in LF data).

Thats means I only have 1 aged cod to infer age to all other cods from the LF data.

On line 144, there is a need that `cola` only keep ages where I have a least 1 non-NA value in the column. By doing so, the present strata will be flagged at line 151.

What do you think? Should line 154 also mention in the message to perhaps increase `thresh.al`?

https://github.com/iml-assess/catchR/blob/f723a376b44f8f143ab4304d86234e43bb9b9952/R/get.samples.R#L143-L163

**Comment by elisvb** [comment]
This was fixed so that it's kept for fill.multinorm and removed after.
