### ISSUE TITLE
date_deb vs date_cap issues for mackerel and capelin

### ISSUE THREAD

**Issue by adsmithca** [iml-assess/catchR#57]
In the mackerel and capelin landings data, the regional stats bureaus attribute a landing date to January 1st as a convention when the data is NA. The way read.ziff is coded makes it so these values are then attributed to the following year eg. 01-01-2018 becomes 01-01-2019 and this creates errors when summing landings across years. This is because date_cap is used instead of date_deb when creating the year variable. In the case of mackerel date_cap is ~49% NA whereas date_deb is 0% NA. There are only  8 cases where capture date was december 31st and the landing date was january 1st of the next year. This issue only for the years 2015:2021 and may just be the way the csv is formatted vs previous years. Suggest changing the script so that year, month, day etc. are derived from date_deb instead of dat_cap and then alerting the user to manually hardcode the changes needed to correct the cases where caught on dec 31 and landed the following jan 1.

**Comment by jordanoplante** [comment]
After discussion, considered solved.
