### ISSUE TITLE
2015:2019

### ISSUE THREAD

**Issue by adsmithca** [iml-assess/catchR#58]
ziff$catch values are 2x the landings in a given year for the years 2015:2019 when compared to the version totale csv ... at least for mackerel.

e.g. 
sum of landings in 2015
csv = 4280.279;  catchR = 8560.558; difference = 4280.279

Can't see where in the function this is bugging and why only in those years.

**Comment by jordanoplante** [comment]
J'ai validé pour 2015 et la problématique n'est pas la fonction `catchR::read.ziff()`, mais bien les données utilisées en intrants. J'arrive exactement à 4280.279 tonnes avec `catchR::read.ziff()` ou en roulant manuellement. Je ne sais pas quelle version de données tu as, mais d'autres biologistes ont soulevé cette problématique l'automne dernier.
